# Numpy Assignment


**Name:Shariq Zeib**


**Roll NO:PIAIC87963**

**COURSE:AI**

**Batch 35**

In [1]:
import numpy as np

In [2]:
my_list=np.arange(10)

In [3]:
my_list

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
my_list2=np.full((3,3),True,dtype=bool)

In [5]:
my_list2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [6]:
my_list3=np.arange(15)

In [7]:
my_list3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
my_list4=np.reshape(my_list3,(3,5))

In [9]:
my_list4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
my_list4.dtype

dtype('int32')

In [11]:
my_list4.shape

(3, 5)

In [12]:
my_list4.argmin()

0

In [13]:
my_list4.argmax()


14

In [14]:
my_list4.argmin(axis=0)

array([0, 0, 0, 0, 0], dtype=int64)

In [15]:
my_list4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
my_list15=my_list4.ravel()

In [17]:
my_list15

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
my_list5=np.arange(10).reshape(2,-1)


In [19]:
my_list6=np.repeat(1,10).reshape(2,-1)

In [20]:
np.concatenate([my_list5,my_list6],axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [21]:
np.concatenate([my_list5,my_list6],axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [22]:
my_list7=np.array([1,2,3])

In [23]:
np.r_[np.repeat(my_list7,3),np.tile(my_list7,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [24]:
my_list8=np.array([1,2,3,2,3,4,3,4,5,6])

In [25]:
my_list9=np.array([7,2,10,2,7,4,9,4,9,8])

In [26]:
np.intersect1d(my_list8,my_list9)

array([2, 4])

In [27]:
my_list10=np.array([1,2,3,4])

In [28]:
my_list11=np.array([5,6,7,8])

In [29]:
np.setdiff1d(my_list10,my_list11)

array([1, 2, 3, 4])

In [30]:
np.where(my_list8 == my_list9)

(array([1, 3, 5, 7], dtype=int64),)

In [31]:
my_list12=np.array([2,6,1,9,10,3,27])


In [32]:
my_list12[(my_list12>=5)&(my_list12<=10)]

array([ 6,  9, 10])

In [33]:
my_list13=np.array([5,7,9,8,7,4,5])
my_list14=np.array([6,3,4,8,9,7,1])

In [34]:
def maxx(x,y):
    if x>=y:
        return x
    else:
        return y
pair_max=np.vectorize(maxx,otypes=[float])



pair_max(my_list13,my_list14)

array([6., 7., 9., 8., 9., 7., 5.])

In [35]:
my_list16=np.arange(9).reshape(3,3)

In [36]:
my_list16

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
my_list16[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [38]:
my_list16[[0,1,2],:]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
my_list16[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [40]:
my_list17=np.array([[1,2,4],[5,6,7],[4,4,7],[6,8,0],[1,4,6]])

In [41]:
my_list17

array([[1, 2, 4],
       [5, 6, 7],
       [4, 4, 7],
       [6, 8, 0],
       [1, 4, 6]])

In [42]:
my_list17[(my_list17 >=5) & (my_list17<=10)]

array([5, 6, 7, 7, 6, 8, 6])

In [43]:
rand_my_list=np.random.randint(low=5,high=10, size=(5,3))+np.random.random((5,3))

In [44]:
rand_my_list

array([[9.18144683, 9.68231945, 7.67247029],
       [6.95100638, 7.43056977, 6.6238064 ],
       [5.45957988, 5.31550889, 9.48391166],
       [6.39159952, 8.229394  , 6.29866505],
       [8.72664833, 8.01001828, 6.77004437]])

In [45]:
rand_my_list2=np.random.random((5,3))

In [46]:
rand_my_list2

array([[0.89074767, 0.75559529, 0.63613657],
       [0.1367858 , 0.79842479, 0.03063524],
       [0.2491718 , 0.51895043, 0.05754791],
       [0.4030043 , 0.16564945, 0.35042498],
       [0.45270833, 0.6284698 , 0.17809056]])

In [47]:
rand_my_list2.shape


(5, 3)

In [48]:
rand_my_list2.ndim

2

In [49]:
rand_my_list2=np.random.random([5,3])

In [50]:
rand_my_list2

array([[0.04758678, 0.93058536, 0.13863886],
       [0.29388892, 0.30459016, 0.46577764],
       [0.47583777, 0.12804028, 0.65863948],
       [0.86761225, 0.12680416, 0.91885431],
       [0.95925265, 0.38406142, 0.94124651]])

In [51]:
np.set_printoptions(precision=5)

In [52]:
rand_my_list2[:4]

array([[0.04759, 0.93059, 0.13864],
       [0.29389, 0.30459, 0.46578],
       [0.47584, 0.12804, 0.65864],
       [0.86761, 0.1268 , 0.91885]])

In [53]:
np.set_printoptions(suppress=False)

In [54]:
np.random.seed(100)

In [55]:
rand_my_list3=np.random.random([3,3])/1e3

In [56]:
rand_my_list3

array([[5.43405e-04, 2.78369e-04, 4.24518e-04],
       [8.44776e-04, 4.71886e-06, 1.21569e-04],
       [6.70749e-04, 8.25853e-04, 1.36707e-04]])

In [57]:
np.set_printoptions(suppress=True,precision=8)

In [58]:
rand_my_list3

array([[0.0005434 , 0.00027837, 0.00042452],
       [0.00084478, 0.00000472, 0.00012157],
       [0.00067075, 0.00082585, 0.00013671]])

In [59]:
np.set_printoptions(threshold=6)

In [60]:
my_list18=np.arange(15)

In [61]:
my_list18

array([ 0,  1,  2, ..., 12, 13, 14])